name: fhtwzadmin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  date_field: ^6.0.3+1
  dio: ^5.9.0
  file_saver: ^0.3.1
  flutter_dotenv: ^6.0.0
  google_nav_bar: ^5.0.7
  http: ^1.5.0
  intl: ^0.20.2
  pdf: ^3.11.3
  printing: ^5.14.2
  shared_preferences: ^2.5.3
  toastification: ^3.0.3
  sidebarx: ^0.17.2
  flutter_bootstrap5: ^1.1.1+1
  file_picker: ^10.3.3
  flutter_excel: ^1.0.1
  csv: ^6.0.0
  uuid: ^4.5.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

